# === PKey and FKey Mapping from Schema ===
pkey_mapping = {
    "Almacenes": "IdAlmacen",
    "Articulos": "IdArticulo",
    "BonosPresencia": "IdBonoPresencia",
    "BonosTrabajadas": "IdBonoTrabajadas",
    "Clientes": "IdCliente",
    "Compras": "IdCompra",
    "Empresas": "IdEmpresa",
    "Invertidas": "IdBonoInvertidas",
    "Operarios": "IdOperario",
    "OrdenesReparacion": "IdOrdenReparacion",
    "OrdenesVentaMostrador": "IdOrdenVentaMostrador",
    "OrdenesVentaTaller": "IdOrdenVentaTaller",
    "Stock": "IdStock",
    "Talleres": "IdTaller",
    "TiposHoras": "IdTipoHoras",
    "TiposOrdenesReparacion": "IdTipoOrdenReparacion",
    "TiposVentasAlmacen": "IdTipoVenta",
    "Vehiculos": "IdVehiculo",
}

fkey_mapping = {
    "Almacenes": {
        "FkEmpresa": {
            "tbl": "Empresas",
            "select_columns": ["IdEmpresa", "Codigo"],
            "left_on": ["Empresa"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdEmpresa": "FkEmpresa"},
        }
    },
    "Articulos": {
        "FkAlmacen": {
            "tbl": "Almacenes",
            "select_columns": ["IdAlmacen", "Codigo"],
            "left_on": ["Almacen"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdAlmacen": "FkAlmacen"}
        }
    },
    "BonosPresencia": {
        "FkTipoHoras": {
            "tbl": "TiposHoras",
            "select_columns": ["IdTipoHoras", "Codigo"],
            "left_on": ["TipoHora"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdTipoHoras": "FkTipoHoras"},
        },
        "FkTaller": {
            "tbl": "Talleres",
            "select_columns": ["IdTaller", "Codigo"],
            "left_on": ["Taller"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdTaller": "FkTaller"},
        },
        "FkOperario": {
            "tbl": "Operarios",
            "select_columns": ["IdOperario", "Codigo"],
            "left_on": ["Operario"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdOperario": "FkOperario"},
        },
    },
    "BonosTrabajadas": {
        "FkOperario": {
            "tbl": "Operarios",
            "select_columns": ["IdOperario", "Codigo"],
            "left_on": ["Operario"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdOperario": "FkOperario"},
        },
        "FkOrdenReparacion": {
            "tbl": "OrdenesReparacion",
            "select_columns": ["IdOrdenReparacion", "ReferenciaOR"],
            "left_on": ["ReferenciaOR"], # "FechaApertura"], ### ¿Es inecesaria la fecha?????????? CUIDADOOOOOOOO No lo sé
            "right_on": ["ReferenciaOR"], #, "Fecha"],
            "pk_to_fk": {"IdOrdenReparacion": "FkOrdenReparacion"},
        },
    },
    "Compras": {
        "FkAlmacen": {
            "tbl": "Almacenes",
            "select_columns": ["IdAlmacen", "Codigo"],
            "left_on": ["Almacen"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdAlmacen": "FkAlmacen"},
        },
        # "FkArticulo": {
        #     "tbl": "Articulos",
        #     "select_columns": ["IdArticulo", "Articulo"],
        #     "left_on": ["Articulo", "FkAlmacen"],
        #     "right_on": ["Articulo", "FkAlmacen"],
        #     "pk_to_fk": {"IdArticulo": "FkArticulo"},
        # },
        # "FkCuenta": {
        #     "tbl": "Clientes",
        #     "select_columns": ["IdCliente", "Codigo"],
        #     "left_on": ["Cliente"],
        #     "right_on": ["Codigo"],
        #     "pk_to_fk": {"IdCliente": "FkCuenta"},
        # }
    },
    "Invertidas": {
        "FkOperario": {
            "tbl": "Operarios",
            "select_columns": ["IdOperario", "Codigo"],
            "left_on": ["Operario"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdOperario": "FkOperario"},
        },
        "FkOrdenReparacion": {
            "tbl": "OrdenesReparacion",
            "select_columns": ["IdOrdenReparacion", "ReferenciaOR"],
            "left_on": ["ReferenciaOR"], #, "FechaApertura"],
            "right_on": ["ReferenciaOR"], #, "FechaApertura"],
            "pk_to_fk": {"IdOrdenReparacion": "FkOrdenReparacion"},
        },
    },
    "OrdenesReparacion": {
        "FkTipoOrdenReparacion": {
            "tbl": "TiposOrdenesReparacion",
            "select_columns": ["IdTipoOrdenReparacion", "Codigo"],
            "left_on": ["TipoOR"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdTipoOrdenReparacion": "FkTipoOrdenReparacion"},
        },
        "FkTaller": {
            "tbl": "Talleres",
            "select_columns": ["IdTaller", "Codigo"],
            "left_on": ["Taller"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdTaller": "FkTaller"},
        },
        "FkVehiculo": {
            "tbl": "Vehiculos",
            "select_columns": ["IdVehiculo", "Bastidor"],
            "left_on": ["Bastidor"],
            "right_on": ["Bastidor"],
            "pk_to_fk": {"IdVehiculo": "FkVehiculo"},
        },
        "FkCuentaCargo": {
            "tbl": "Clientes",
            "select_columns": ["IdCliente", "Codigo"],
            "left_on": ["CuentaCargo"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdCliente": "FkCuentaCargo"},
        },
        "FkCuentaTitular": {
            "tbl": "Clientes",
            "select_columns": ["IdCliente", "Codigo"],
            "left_on": ["CuentaTitular"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdCliente": "FkCuentaTitular"},
        },
    },
    "OrdenesVentaMostrador": {
        "FkTipoVenta": {
            "tbl": "TiposVentasAlmacen",
            "select_columns": ["IdTipoVenta", "Codigo"],
            "left_on": ["TipoVenta"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdTipoVenta": "FkTipoVenta"},
        },
        "FkArticulo": {
            "tbl": "Articulos",
            "select_columns": ["IdArticulo", "Referencia"],
            "left_on": ["Articulo"],
            "right_on": ["Referencia"],
            "pk_to_fk": {"IdArticulo": "FkArticulo"},
        },
        "FkCliente": {
            "tbl": "Clientes",
            "select_columns": ["IdCliente", "Codigo"],
            "left_on": ["Cliente"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdCliente": "FkCliente"},
        },
        "FkAlmacen": {
            "tbl": "Almacenes",
            "select_columns": ["IdAlmacen", "Codigo"],
            "left_on": ["Almacen"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdAlmacen": "FkAlmacen"},
        },
    },
    "OrdenesVentaTaller": {
        "FkTipoVenta": {
            "tbl": "TiposVentasAlmacen",
            "select_columns": ["IdTipoVenta", "Codigo"],
            "left_on": ["TipoVenta"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdTipoVenta": "FkTipoVenta"},
        },
        "FkCliente": {
            "tbl": "Clientes",
            "select_columns": ["IdCliente", "Codigo"],
            "left_on": ["Cliente"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdCliente": "FkCliente"},
        },
        "FkArticulo": {
            "tbl": "Articulos",
            "select_columns": ["IdArticulo", "Referencia"],
            "left_on": ["Articulo"],
            "right_on": ["Referencia"],
            "pk_to_fk": {"IdArticulo": "FkArticulo"},
        },
        "FkOrdenReparacion": {
            "tbl": "OrdenesReparacion",
            "select_columns": ["IdOrdenReparacion", "ReferenciaOR"],
            "left_on": ["ReferenciaOR"],
            "right_on": ["ReferenciaOR"],
            "pk_to_fk": {"IdOrdenReparacion": "FkOrdenReparacion"},
        },
        "FkAlmacen": {
            "tbl": "Almacenes",
            "select_columns": ["IdAlmacen", "Codigo"],
            "left_on": ["Almacen"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdAlmacen": "FkAlmacen"},
        },
    },
    "Stock": {
        "FkAlmacen": {
            "tbl": "Almacenes",
            "select_columns": ["IdAlmacen", "Codigo", "ReferenciaArticulo"],
            "left_on": ["Almacen"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdAlmacen": "FkAlmacen"},
        },
        "FkArticulo": {
            "tbl": "Articulos",
            "select_columns": ["IdArticulo", "Referencia"],
            "left_on": ["Articulo"],
            "right_on": ["Referencia"],
            "pk_to_fk": {"IdArticulo": "FkArticulo"},
        },
    },
    "Talleres": {
        "FkEmpresa": {
            "tbl": "Empresas",
            "select_columns": ["IdEmpresa", "Codigo"],
            "left_on": ["Empresa"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdEmpresa": "FkEmpresa"},
        }
    },
    "Operarios": {
        "FkTaller": {
            "tbl": "Talleres",
            "select_columns": ["IdTaller", "Codigo"],
            "left_on": ["Taller"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdTaller": "FkTaller"},
        }
    },
    "Vehiculos": {
        "FkCuentaCliente": {
            "tbl": "Clientes",
            "select_columns": ["IdCliente", "Codigo"],
            "left_on": ["CuentaCliente"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdCliente": "FkCuentaCliente"},
        },
        "FkCuentaTitular": {
            "tbl": "Clientes",
            "select_columns": ["IdCliente", "Codigo"],
            "left_on": ["CuentaTitular"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdCliente": "FkCuentaTitular"},
        },
        "FkCuentaConductor": {
            "tbl": "Clientes",
            "select_columns": ["IdCliente", "Codigo"],
            "left_on": ["CuentaConductor"],
            "right_on": ["Codigo"],
            "pk_to_fk": {"IdCliente": "FkCuentaConductor"},
        },
    },
    "Presupuestos":{
        "FkOperario":{
            "tbl": "Seccion",
            "select_columns": ['IdSeccion', 'Seccion'],
            "left_on": ["Seccion"],
            "right_on": ["Seccion"],
            "pk_to_fk": {"IdSeccion": "FkSeccion"}
        }
    }
}

# Skeleton mapping for FK column relations between Silver and Gold schemas
fk_column_silver_mapping = {
    "Vehiculos": {
        "FkCuentaCliente": ("Codigo", "CuentaCliente"),
        "FkCuentaTitular": ("Codigo", "CuentaTitular"),
        "FkCuentaConductor": ("Codigo", "CuentaConductor"),
    },
    "OrdenesReparacion": {
        "FkCliente Cuenta Cargo": "CuentaCargo",
        "FkCliente Cuenta Titular": "CuentaTitular",
    },
    "Compras": {
        "FkAlmacen": "Almacen",
        "FkCliente": "Cliente",
        "FkArticulo": "Articulo",
    },
    "BonosTrabajadas": {
        "FkOperario": "Operario",
        "FkOrdenReparacion": "ReferenciaOR",
    },
    "BonosPresencia": {
        "FkTaller": "Taller",
        "FkOperario": "Operario",
        "FkTipoHoras": "TipoHora",
    },
    # Add more tables and their mappings here
}


column_name_mapping = {
    "Almacenes": {"Codigo": "Codigo", "Nombre": "Nombre", "Empresa": None},
    "Articulos": {
        "Mar": "Mar",
        "Referencia": "Referencia",
        "Articulo": "Articulo",
        "Denominacion": "Denominacion",
        "Almacen": None,
        "Familia": "Familia",
        "PVP": "PVP",
        "ClaveDTO": "ClaveDTO",
        "FechaAlta": "FechaAlta",
    },
    "BonosPresencia": {
        "Taller": None,
        "Fecha": "Fecha",
        "Seccion": None,
        "Operario": None,
        "NombreOperario": None,
        "EntradaPresencia": "EntradaPresencia",
        "SalidaPresencia": "SalidaPresencia",
        "DiferenciaPresencia": "DiferenciaPresencia",
        "TipoHora": None,
    },
    "BonosTrabajadas": {
        "Taller": None,
        "Fecha": "Fecha",
        "Seccion": None,
        "Operario": None,
        "NombreOperario": None,
        "ReferenciaOR": None,
        "TipoOR": None,
        "IDV": None,
        "Matricula": None,
        "Entrada": "Entrada",
        "Salida": "Salida",
        "DiferenciaTrabajadas": None,
    },
    "Clientes": {
        "Codigo": "Codigo",
        "Categoria": "Categoria",
        "Nombre": "Nombre",
        "DNI/CIF": "DNI/CIF",
        "Direccion": "Direccion",
        "CodigoPostal": "CodigoPostal",
        "Localidad": "Localidad",
        "CorreoElectronico": "CorreoElectronico",
    },
    "Compras": {
        "Almacen": None,
        "Fecha": "Fecha",
        "ReferenciaCompra": "ReferenciaCompra",
        "Cuenta": "FkCuenta",
        "NombreProveedor": "NombreProvedor",
        "T.com": "T.Com",
        "Albaran": "Albaran",
        "Articulo": None,
        "Mar": None,
        "Articulo1": None,
        "Denominacion": None,
        "Clave": "ClaveDTO",
        "Familia": None,
        "Fam.apro": None,
        "F.Market": None,
        "Cantidad": "Cantidad",
        "PrecioCompra": "P.Compra",
        "TotalCompra": "TotalCompra",
        "PVP": "PVP",
    },
    "Talleres": {"Codigo": "Codigo", "Nombre": "Nombre", "Empresa": None},
    "Vehiculos": {
        "IDV": "IDV",
        "Matricula": "Matricula",
        "Bastidor": "Bastidor",
        "Mar": "Mar",
        "Modelo": "Modelo",
        "CuentaTitular": None,
        "CuentaCliente": None,
        "CuentaConductor": None,
        "FechaMatriculacion": "FechaMatriculacion",
        "Kilometros": "Kilometros",
        "FechaUltimo": "FechaUltimaVisita",
        "Familia": "Familia",
        "CodigoModelo": "CodigoModelo",
    },
    "OrdenesReparacion": {
        "Taller": None,
        "ReferenciaOR": "Referencia",
        "IDV": "IDV",
        "Matricula": None,
        "CuentaCargo": None,
        "CuentaTitular": None,
        "NombreCliente": None,
        "DNI/CIF": None,
        "CodigoPostal": None,
        "Marca": None,
        "TipoOR": None,
        "Recep": "Recep",
        "FechaApertura": "FechaApertura",
        "HoraCreacion": None,
        "FechaCierre": "FechaCierre",
        "Hora": None,
        "FechaPrimera": "FechaPrimero",
        "FechaUltimo": "FechaUltimo",
        "TiempoFacturado": "TiempoFac",
        "TiempoInvertido": "TiempoInvertido",
        "DiferenciaTiempo": None,
        "Base": "Base",
        "ManoObra": "ManoObra",
        "ManoObraSub": "MoSub",
        "Recambio": "Recamb",
        "CostoManoObra": "CostoSub",
        "CostoSub": "CostoSub",
        "CostoRecambio": "CostoRec",
        "NumeroLocal": "NroLocal",
        "Est": None,
        "Serie": None,
        "Bastidor": None,
        "CuentaTitular": None,
    },
    "TiposHoras": {"Codigo": "Codigo", "Descripcion": "Descripcion"},
    "TiposVentasAlmacen": {"Codigo": "Codigo", "Descripcion": "Descripcion"},
    "TiposOrdenesReparacion": {"Codigo": "Codigo", "Descripcion": "Descripcion"},
    "Stock": {
        "Almacen": None,
        "Articulo": None,
        "Mar": None,
        "ReferenciaArticulo": None,
        "Descripcion": None,
        "Grupo": None,
        "Familia": None,
        "Fam.apro": None,
        "F.Marketin": None,
        "ClaveDescuento": None,
        "PVP": None,
        "CostoMedio": "CostoMedio",
        "Existencia": "Existencia",
        "ValorStock": "ValorStock",
        "FechaUltimaEntrada": "F.ul.ent",
        "FechaUltimaSalida": "F.ulsal",
        "Cat": "Cat",
    },
    "OrdenesVentaMostrador": {
        "Almacen": None,
        "Referencia": "Referencia",
        "Serie": "SerieNum",
        "Fecha": "Fecha",
        "Cuenta": None,
        "NombreCliente": None,
        "DNI/CIF": None,
        "CodigoPostal": None,
        "TipoCliente": None,
        "Canal": "Canal",
        "Vendedor": "Vende",
        "TipoVenta": None,
        "Marca": None,
        "Articulo": None,
        "Denominacion": None,
        "Fam.apro": None,
        "F.Marketin": None,
        "Familia": None,
        "Grupo": None,
        "Cantidad": "Can",
        "PVP": "PVP",
        "Descuento": "Dto",
        "Neto": "Neto",
        "Costo": "Costo",
        "PorcentajeBeneficio": None,
        "Beneficio": None,
    },
    "OrdenesVentaTaller": {
        "Almacen": None,
        "ReferenciaVentaTaller": None,
        "TipoVenta": None,
        "Recep": "Recep",
        "TipoCliente": "TipoCliente",
        "Cuenta": None,
        "NombreCliente": None,
        "DNI/CIF": None,
        "CodigoPostal": None,
        "FechaSalida": "FechaSalida",
        "FechaCierre": "FechaCierre",
        "Articulo": None,
        "Denominacion": None,
        "Familia": None,
        "Fam.a": None,
        "F.Marketin": None,
        "Grupo": None,
        "ClaveDescuento": "ClaveDto",
        "Cantidad": "Canti",
        "PVP": "PVP",
        "Descuento": "Dto",
        "Neto": "Neto",
        "Costo": "Costo",
        "Beneficio": None,
    },
    "BonosTrabajadas": {
        "Taller": None,
        "Fecha": "Fecha",
        "Seccion": None,
        "Operario": None,
        "NombreOperario": None,
        "ReferenciaOR": None,
        "TipoOR": None,
        "IDV": None,
        "Matricula": None,
        "Entrada": "Entrada",
        "Salida": "Salida",
        "DiferenciaTrabajadas": None,
    },
    "Invertidas": {
        "Taller": None,
        "ReferenciaOR": None,
        "FechaApertura": "FechaApertura",
        "FechaCierre": "FechaCierra",
        "Matricula": None,
        "CuentaCargo": None,
        "TipoOR": None,
        "TipoFactura": "TipoFactura",
        "Recep": "Recep",
        "Operario": None,
        "TiempoAsignado": "TiempoAsignado",
        "TiempoInvertido": "TiempoInvertido",
        "Bastidor": None,
    },
    "Operarios": {
        "Codigo": "Codigo",
        "Nombre": "Nombre",
        "Seccion": "Seccion",
        "Taller": None,
        "Activo": "Activo",
    },
    "Empresas": {"Codigo": "Codigo", "Nombre": "Nombre"},
}
